version: '3'

name: devcode_container

volumes:
  mysql_volume:

networks:
  go_network:

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart : always
    networks:
      - go_network
    ports:
      - 3301:3306
    volumes:
    - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=devcode

    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
    #   interval: 2s
    #   timeout: 2s
    #   retries: 20
  godev:
    container_name: godev
    image: yogawahyudi7/devcode-golang:v1.15
    restart : on-failure
    networks:
      - go_network
    ports:
      - 3030:3030
    environment:
      - MODE=DEV
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3301
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DBNAME=devcode
    # depends_on:
    #   mysql:
    #     condition: service_healthy

    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 2s
    #     max_attempts: 2
    #     window: 120s

  



